name: Update Notion with GitHub Releases

on:
  release:
    types: [published]

jobs:
  update-notion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run the script
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        # NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      run: python .github/notionScript.py  
