name: Release Drafter2

on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: write
  pull-requests: read
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
